// Code generated by sqlc. DO NOT EDIT.
// source: consumption.sql

package sqlcdb

import (
	"context"
	"time"
)

const insertConsumption = `
INSERT INTO consumption
    (user_id, product_id, quantity, unit_price, total_price)
VALUES
    ($1::uuid, $2, $3, $4, $5)
`

// InsertConsumptionParams — параметры для InsertConsumption.
type InsertConsumptionParams struct {
	UserID     string  `json:"user_id"`
	ProductID  string  `json:"product_id"`
	Quantity   float64 `json:"quantity"`
	UnitPrice  float64 `json:"unit_price"`
	TotalPrice float64 `json:"total_price"`
}

// InsertConsumption вставляет одну строку потребления.
// Вызывается в цикле внутри транзакции.
func (q *Queries) InsertConsumption(ctx context.Context, arg InsertConsumptionParams) error {
	_, err := q.db.ExecContext(ctx, insertConsumption,
		arg.UserID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	return err
}

const getConsumptionByUser = `
SELECT product_id, quantity, unit_price, total_price, calculated_at
FROM   consumption
WHERE  user_id = $1::uuid
ORDER  BY calculated_at DESC
`

// GetConsumptionByUserRow — одна строка результата GetConsumptionByUser.
type GetConsumptionByUserRow struct {
	ProductID    string    `json:"product_id"`
	Quantity     float64   `json:"quantity"`
	UnitPrice    float64   `json:"unit_price"`
	TotalPrice   float64   `json:"total_price"`
	CalculatedAt time.Time `json:"calculated_at"`
}

// GetConsumptionByUser возвращает историю потребления пользователя.
func (q *Queries) GetConsumptionByUser(ctx context.Context, userID string) ([]GetConsumptionByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getConsumptionByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []GetConsumptionByUserRow
	for rows.Next() {
		var r GetConsumptionByUserRow
		if err := rows.Scan(
			&r.ProductID,
			&r.Quantity,
			&r.UnitPrice,
			&r.TotalPrice,
			&r.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

const sumConsumptionByUser = `
SELECT COALESCE(SUM(total_price), 0)::numeric AS total
FROM   consumption
WHERE  user_id = $1::uuid
`

// SumConsumptionByUser возвращает накопленную сумму затрат пользователя.
func (q *Queries) SumConsumptionByUser(ctx context.Context, userID string) (float64, error) {
	var total float64
	err := q.db.QueryRowContext(ctx, sumConsumptionByUser, userID).Scan(&total)
	return total, err
}
