// Code generated by sqlc. DO NOT EDIT.
// Versions:
//   sqlc v1.25.0
// Source: sqlc.yaml

package sqlcdb

import (
	"context"
	"database/sql"
)

// DBTX — общий интерфейс для *sql.DB и *sql.Tx.
// Позволяет использовать одни и те же методы как с обычным соединением,
// так и внутри транзакции (WithTx).
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// New создаёт Queries поверх *sql.DB.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries — все сгенерированные методы запросов.
type Queries struct {
	db DBTX
}

// WithTx возвращает новый Queries работающий внутри транзакции.
// Используется в ConsumptionRepository.SaveBatch.
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
