// Code generated by sqlc. DO NOT EDIT.

package sqlcdb

import (
	"time"
)

// Product соответствует строке таблицы products.
type Product struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	PricePerUnit float64   `json:"price_per_unit"`
	Unit         string    `json:"unit"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// User соответствует строке таблицы users.
type User struct {
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

// Consumption соответствует строке таблицы consumption.
type Consumption struct {
	ID           int64     `json:"id"`
	UserID       string    `json:"user_id"`
	ProductID    string    `json:"product_id"`
	Quantity     float64   `json:"quantity"`
	UnitPrice    float64   `json:"unit_price"`
	TotalPrice   float64   `json:"total_price"`
	CalculatedAt time.Time `json:"calculated_at"`
}
