// Code generated by sqlc. DO NOT EDIT.
// source: products.sql

package sqlcdb

import (
	"context"

	"github.com/lib/pq"
)

const getProductsByIDs = `
SELECT id, name, price_per_unit, unit, updated_at
FROM   products
WHERE  id = ANY($1::text[])
`

// GetProductsByIDs загружает продукты по списку id одним запросом.
func (q *Queries) GetProductsByIDs(ctx context.Context, ids []string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Product
	for rows.Next() {
		var p Product
		if err := rows.Scan(
			&p.ID,
			&p.Name,
			&p.PricePerUnit,
			&p.Unit,
			&p.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

const listProducts = `
SELECT id, name, price_per_unit, unit, updated_at
FROM   products
ORDER  BY id
`

// ListProducts возвращает полный справочник продуктов.
func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Product
	for rows.Next() {
		var p Product
		if err := rows.Scan(
			&p.ID,
			&p.Name,
			&p.PricePerUnit,
			&p.Unit,
			&p.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}
