// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package sqlcdb

import "context"

const upsertUser = `
INSERT INTO users (user_id)
VALUES ($1::uuid)
ON CONFLICT (user_id) DO NOTHING
`

// UpsertUser создаёт пользователя если не существует.
func (q *Queries) UpsertUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, upsertUser, userID)
	return err
}
